[workspace]
members = ["oxde-agent", "oxde-db", "oxde-hub", "oxde-models", "oxde-proto", "xtask"]
resolver = "3"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"

[workspace.dependencies]
anyhow = "1.0.104"
argon2 = "0.5.3"
axum = "0.8.9"
axum-server = "0.8.0"
base64 = "0.23.0"
bollard = "0.21.0"
bytes = "1.12.1"
futures-util = "0.3.33"
gix = "0.86.0"
hyper-util = "0.1.20"
jiff = "0.2.35"
oxde-db = { path = "oxde-db" }
oxde-models = { path = "oxde-models" }
oxde-proto = { path = "oxde-proto" }
papaya = "0.2.4"
prost = "0.14.4"
rand = "0.10.2"
rcgen = "0.14.8"
rmcp = "3.1.0"
rust-embed = "8.12.0"
rustls = "0.23.43"
schemars = "1.2.2"
serde = "1.0.229"
serde_json = "1.0.151"
sha2 = "0.11.0"
sysinfo = "0.39.6"
thiserror = "2.0.19"
toasty = "0.9.0"
toasty-cli = "0.9.0"
toasty-core = "0.9.0"
tokio = "1.53.1"
tokio-stream = "0.1.19"
tonic = "0.14.6"
tonic-prost = "0.14.6"
tonic-prost-build = "0.14.6"
toml = "1.1.4"
tower = "0.5.3"
tower-http = "0.7.0"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
ts-rs = "12.0.1"
uuid = "1.24.0"
zip = "8.6.0"
