version = 1

[[migrations]]
id = 7955213190850656469
name = "0000_create_users.sql"
snapshot_name = "0000_snapshot.toml"

[[migrations]]
id = 8956383277855373474
name = "0001_create_apps_and_deployments.sql"
snapshot_name = "0001_snapshot.toml"

[[migrations]]
id = 2335849023580041425
name = "0002_add_api_tokens.sql"
snapshot_name = "0002_snapshot.toml"

[[migrations]]
id = 2059858138358139711
name = "0003_add_hosts.sql"
snapshot_name = "0003_snapshot.toml"

[[migrations]]
id = 7681455421660324928
name = "0004_add_app_host_id.sql"
snapshot_name = "0004_snapshot.toml"
