version = 1

[[migrations]]
id = 7955213190850656469
name = "0000_create_users.sql"
snapshot_name = "0000_snapshot.toml"

[[migrations]]
id = 8956383277855373474
name = "0001_create_apps_and_deployments.sql"
snapshot_name = "0001_snapshot.toml"

[[migrations]]
id = 2335849023580041425
name = "0002_add_api_tokens.sql"
snapshot_name = "0002_snapshot.toml"
