[package]
name = "oxde-agent"
edition = "2024"

[dependencies]
anyhow.workspace = true
oxde-proto.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tonic.workspace = true
tonic-prost.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[lints]
workspace = true
